/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPoem {
  'id' : PoemId,
  'title' : string,
  'content' : string,
  'category' : string,
}
export type AdminPoemResult = { 'contentTooShort' : null } |
  { 'categoryTooShort' : null } |
  { 'titleTooShort' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null } |
  { 'success' : AdminPoem };
export interface CommunityPoem {
  'id' : PoemId,
  'title' : string,
  'content' : string,
  'suggestedTheme' : Theme,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type DeleteResult = { 'notFoundInAdminCollection' : null } |
  { 'notFoundInCommunityCollection' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null } |
  { 'success' : null };
export type PoemDeleteResult = { 'notFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null };
export type PoemId = bigint;
export type PoemResult = { 'contentTooShort' : null } |
  { 'authorNameTooShort' : null } |
  { 'titleTooShort' : null } |
  { 'notFound' : null } |
  { 'themeNameTooShort' : null } |
  { 'success' : CommunityPoem } |
  { 'unauthorized' : null };
export interface Theme { 'name' : string, 'description' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminPoem' : ActorMethod<[string, string, string], AdminPoemResult>,
  'changeAdminPassword' : ActorMethod<[string, string], ChangePasswordResult>,
  'resetAdminPassword' : ActorMethod<[string], ChangePasswordResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAdminPoem' : ActorMethod<[PoemId], DeleteResult>,
  'deleteMyPoem' : ActorMethod<[PoemId], PoemDeleteResult>,
  'getAdminPoems' : ActorMethod<[], Array<AdminPoem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPoems' : ActorMethod<[], Array<CommunityPoem>>,
  'getDisplayName' : ActorMethod<[Principal], [] | [string]>,
  'getMyPoems' : ActorMethod<[], Array<CommunityPoem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'submitPoem' : ActorMethod<[string, string, string], PoemResult>,
  'updateAdminPoem' : ActorMethod<[PoemId, string, string, string], AdminPoemResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];