/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminPoem = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const AdminPoemResult = IDL.Variant({
  'contentTooShort' : IDL.Null,
  'categoryTooShort' : IDL.Null,
  'titleTooShort' : IDL.Null,
  'notFound' : IDL.Null,
  'notAdmin' : IDL.Null,
  'success' : AdminPoem,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PoemId = IDL.Nat;
export const DeleteResult = IDL.Variant({
  'notFoundInAdminCollection' : IDL.Null,
  'notFoundInCommunityCollection' : IDL.Null,
  'notFound' : IDL.Null,
  'notAdmin' : IDL.Null,
  'success' : IDL.Null,
});
export const PoemDeleteResult = IDL.Variant({
  'notFound' : IDL.Null,
  'success' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Theme = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const CommunityPoem = IDL.Record({
  'id' : PoemId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'suggestedTheme' : Theme,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const PoemResult = IDL.Variant({
  'contentTooShort' : IDL.Null,
  'authorNameTooShort' : IDL.Null,
  'titleTooShort' : IDL.Null,
  'notFound' : IDL.Null,
  'themeNameTooShort' : IDL.Null,
  'success' : CommunityPoem,
  'unauthorized' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminPoem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AdminPoemResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAdminPoem' : IDL.Func([PoemId], [DeleteResult], []),
  'deleteMyPoem' : IDL.Func([PoemId], [PoemDeleteResult], []),
  'getAdminPoems' : IDL.Func([], [IDL.Vec(AdminPoem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getMyPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PoemResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminPoem = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const AdminPoemResult = IDL.Variant({
    'contentTooShort' : IDL.Null,
    'categoryTooShort' : IDL.Null,
    'titleTooShort' : IDL.Null,
    'notFound' : IDL.Null,
    'notAdmin' : IDL.Null,
    'success' : AdminPoem,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PoemId = IDL.Nat;
  const DeleteResult = IDL.Variant({
    'notFoundInAdminCollection' : IDL.Null,
    'notFoundInCommunityCollection' : IDL.Null,
    'notFound' : IDL.Null,
    'notAdmin' : IDL.Null,
    'success' : IDL.Null,
  });
  const PoemDeleteResult = IDL.Variant({
    'notFound' : IDL.Null,
    'success' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Theme = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Time = IDL.Int;
  const CommunityPoem = IDL.Record({
    'id' : PoemId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'suggestedTheme' : Theme,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const PoemResult = IDL.Variant({
    'contentTooShort' : IDL.Null,
    'authorNameTooShort' : IDL.Null,
    'titleTooShort' : IDL.Null,
    'notFound' : IDL.Null,
    'themeNameTooShort' : IDL.Null,
    'success' : CommunityPoem,
    'unauthorized' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminPoem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AdminPoemResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAdminPoem' : IDL.Func([PoemId], [DeleteResult], []),
    'deleteMyPoem' : IDL.Func([PoemId], [PoemDeleteResult], []),
    'getAdminPoems' : IDL.Func([], [IDL.Vec(AdminPoem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
    'getDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMyPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PoemResult], []),
  });
};

export const init = ({ IDL }) => { return []; };