/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPoemEntry {
  'id' : PoemId,
  'title' : string,
  'content' : string,
  'category' : string,
}
export type AdminPoemResult = { 'contentTooShort' : null } |
  { 'categoryTooShort' : null } |
  { 'titleTooShort' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null } |
  { 'success' : AdminPoemEntry };
export type ChangePasswordResult = { 'passwordTooShort' : null } |
  { 'incorrectPassword' : null } |
  { 'success' : null };
export type CommentDeleteResult = { 'notFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null };
export type CommentId = bigint;
export interface CommentReply {
  'id' : ReplyId,
  'commentId' : CommentId,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : string,
}
export type CommentResult = { 'textTooShort' : null } |
  { 'success' : PostComment } |
  { 'unauthorized' : null };
export interface CommunityPoem {
  'id' : PoemId,
  'title' : string,
  'content' : string,
  'suggestedTheme' : Theme,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type DeleteResult = { 'notFoundInAdminCollection' : null } |
  { 'notFoundInCommunityCollection' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null } |
  { 'success' : null };
export type NoteDeleteResult = { 'notFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null };
export type NoteId = bigint;
export type NoteResult = { 'contentTooShort' : null } |
  { 'titleTooShort' : null } |
  { 'notFound' : null } |
  { 'success' : UserNote } |
  { 'unauthorized' : null };
export type PoemDeleteResult = { 'notFound' : null } |
  { 'success' : null } |
  { 'unauthorized' : null };
export type PoemId = bigint;
export type PoemResult = { 'contentTooShort' : null } |
  { 'authorNameTooShort' : null } |
  { 'titleTooShort' : null } |
  { 'notFound' : null } |
  { 'themeNameTooShort' : null } |
  { 'success' : CommunityPoem } |
  { 'unauthorized' : null };
export interface PostComment {
  'id' : CommentId,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : string,
}
export type ReplyId = bigint;
export type ReplyResult = { 'commentNotFound' : null } |
  { 'textTooShort' : null } |
  { 'success' : CommentReply } |
  { 'unauthorized' : null };
export interface Theme { 'name' : string, 'description' : string }
export type Time = bigint;
export interface UserNote {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : Time,
  'isPublic' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminPoem' : ActorMethod<[string, string, string], AdminPoemResult>,
  'addComment' : ActorMethod<[string, string, string], CommentResult>,
  'addReply' : ActorMethod<[CommentId, string, string, string], ReplyResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], ChangePasswordResult>,
  'createNote' : ActorMethod<[string, string, boolean], NoteResult>,
  'deleteAdminPoem' : ActorMethod<[PoemId], DeleteResult>,
  'deleteComment' : ActorMethod<[CommentId], CommentDeleteResult>,
  'deleteMyPoem' : ActorMethod<[PoemId], PoemDeleteResult>,
  'deleteNote' : ActorMethod<[NoteId], NoteDeleteResult>,
  'deleteReply' : ActorMethod<[ReplyId], CommentDeleteResult>,
  'getAdminPassword' : ActorMethod<[], string>,
  'getAdminPoems' : ActorMethod<[], Array<AdminPoemEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[string], Array<PostComment>>,
  'getCommunityPoems' : ActorMethod<[], Array<CommunityPoem>>,
  'getDisplayName' : ActorMethod<[Principal], [] | [string]>,
  'getMyNotes' : ActorMethod<[], Array<UserNote>>,
  'getMyPoems' : ActorMethod<[], Array<CommunityPoem>>,
  'getPublicNotesForUser' : ActorMethod<[Principal], Array<UserNote>>,
  'getRepliesForComment' : ActorMethod<[CommentId], Array<CommentReply>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetAdminPassword' : ActorMethod<[string], ChangePasswordResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'submitPoem' : ActorMethod<[string, string, string], PoemResult>,
  'updateAdminPoem' : ActorMethod<
    [PoemId, string, string, string],
    AdminPoemResult
  >,
  'updateNote' : ActorMethod<[NoteId, string, string, boolean], NoteResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];