/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PoemId = IDL.Nat;
export const AdminPoemEntry = IDL.Record({
  'id' : PoemId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
});
export const AdminPoemResult = IDL.Variant({
  'contentTooShort' : IDL.Null,
  'categoryTooShort' : IDL.Null,
  'titleTooShort' : IDL.Null,
  'notFound' : IDL.Null,
  'notAdmin' : IDL.Null,
  'success' : AdminPoemEntry,
});
export const CommentId = IDL.Nat;
export const Time = IDL.Int;
export const PostComment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const CommentResult = IDL.Variant({
  'pendingReview' : IDL.Null,
  'moderationRejected' : IDL.Text,
  'textTooShort' : IDL.Null,
  'success' : PostComment,
  'unauthorized' : IDL.Null,
});
export const ReplyId = IDL.Nat;
export const CommentReply = IDL.Record({
  'id' : ReplyId,
  'commentId' : CommentId,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const ReplyResult = IDL.Variant({
  'pendingReview' : IDL.Null,
  'commentNotFound' : IDL.Null,
  'moderationRejected' : IDL.Text,
  'textTooShort' : IDL.Null,
  'success' : CommentReply,
  'unauthorized' : IDL.Null,
});
export const ModerationId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChangePasswordResult = IDL.Variant({
  'passwordTooShort' : IDL.Null,
  'incorrectPassword' : IDL.Null,
  'success' : IDL.Null,
});
export const NoteId = IDL.Nat;
export const UserNote = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
  'isPublic' : IDL.Bool,
});
export const NoteResult = IDL.Variant({
  'contentTooShort' : IDL.Null,
  'titleTooShort' : IDL.Null,
  'notFound' : IDL.Null,
  'success' : UserNote,
  'unauthorized' : IDL.Null,
});
export const DeleteResult = IDL.Variant({
  'notFoundInAdminCollection' : IDL.Null,
  'notFoundInCommunityCollection' : IDL.Null,
  'notFound' : IDL.Null,
  'notAdmin' : IDL.Null,
  'success' : IDL.Null,
});
export const CommentDeleteResult = IDL.Variant({
  'notFound' : IDL.Null,
  'success' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const PoemDeleteResult = IDL.Variant({
  'notFound' : IDL.Null,
  'success' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const NoteDeleteResult = IDL.Variant({
  'notFound' : IDL.Null,
  'success' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const AboutContent = IDL.Record({
  'bio' : IDL.Text,
  'poetryFragments' : IDL.Text,
  'lastUpdated' : Time,
  'poetName' : IDL.Text,
  'story' : IDL.Text,
});
export const CallSettings = IDL.Record({ 'allowCalls' : IDL.Bool });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Theme = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CommunityPoem = IDL.Record({
  'id' : PoemId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'suggestedTheme' : Theme,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const MessageId = IDL.Nat;
export const DirectMessage = IDL.Record({
  'id' : MessageId,
  'read' : IDL.Bool,
  'text' : IDL.Text,
  'toUser' : IDL.Principal,
  'toUsername' : IDL.Text,
  'timestamp' : Time,
  'fromUser' : IDL.Principal,
  'fromUsername' : IDL.Text,
});
export const ModerationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'needsReview' : IDL.Null,
});
export const ModerationEntry = IDL.Record({
  'id' : ModerationId,
  'status' : ModerationStatus,
  'content' : IDL.Text,
  'contentType' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'riskLevel' : IDL.Text,
  'reason' : IDL.Text,
});
export const ModerationStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'approvedCount' : IDL.Nat,
  'rejectedCount' : IDL.Nat,
});
export const SignalId = IDL.Nat;
export const CallSignalType = IDL.Variant({
  'iceCandidate' : IDL.Null,
  'offer' : IDL.Null,
  'answer' : IDL.Null,
  'hangup' : IDL.Null,
});
export const CallSignal = IDL.Record({
  'id' : SignalId,
  'data' : IDL.Text,
  'toUser' : IDL.Principal,
  'timestamp' : Time,
  'consumed' : IDL.Bool,
  'fromUser' : IDL.Principal,
  'signalType' : CallSignalType,
});
export const SendMessageResult = IDL.Variant({
  'textTooShort' : IDL.Null,
  'success' : DirectMessage,
  'unauthorized' : IDL.Null,
});
export const PoemResult = IDL.Variant({
  'pendingReview' : IDL.Null,
  'contentTooShort' : IDL.Null,
  'authorNameTooShort' : IDL.Null,
  'moderationRejected' : IDL.Text,
  'titleTooShort' : IDL.Null,
  'notFound' : IDL.Null,
  'themeNameTooShort' : IDL.Null,
  'success' : CommunityPoem,
  'unauthorized' : IDL.Null,
});

export const idlService = IDL.Service({
  'addAdminPoem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AdminPoemResult],
      [],
    ),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [CommentResult], []),
  'addReply' : IDL.Func(
      [CommentId, IDL.Text, IDL.Text, IDL.Text],
      [ReplyResult],
      [],
    ),
  'approveModeratedContent' : IDL.Func([ModerationId], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ChangePasswordResult],
      [],
    ),
  'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NoteResult], []),
  'deleteAdminPoem' : IDL.Func([PoemId], [DeleteResult], []),
  'deleteComment' : IDL.Func([CommentId], [CommentDeleteResult], []),
  'deleteMyPoem' : IDL.Func([PoemId], [PoemDeleteResult], []),
  'deleteNote' : IDL.Func([NoteId], [NoteDeleteResult], []),
  'deleteReply' : IDL.Func([ReplyId], [CommentDeleteResult], []),
  'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
  'getAdminPassword' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminPoems' : IDL.Func([], [IDL.Vec(AdminPoemEntry)], ['query']),
  'getCallSettings' : IDL.Func([IDL.Principal], [CallSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCommentsForPost' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PostComment)],
      ['query'],
    ),
  'getCommunityPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
  'getConversationByUsername' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getMessagesForUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getModerationQueue' : IDL.Func([], [IDL.Vec(ModerationEntry)], ['query']),
  'getModerationStats' : IDL.Func([], [ModerationStats], ['query']),
  'getMyNotes' : IDL.Func([], [IDL.Vec(UserNote)], ['query']),
  'getMyPendingSignals' : IDL.Func([], [IDL.Vec(CallSignal)], ['query']),
  'getMyPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicNotesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UserNote)],
      ['query'],
    ),
  'getRepliesForComment' : IDL.Func(
      [CommentId],
      [IDL.Vec(CommentReply)],
      ['query'],
    ),
  'getUserPhotoUrl' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'login' : IDL.Func([], [UserRole], []),
  'markDirectMessageRead' : IDL.Func([MessageId], [], []),
  'markSignalConsumed' : IDL.Func([SignalId], [], []),
  'rejectModeratedContent' : IDL.Func([ModerationId, IDL.Text], [], []),
  'resetAdminPassword' : IDL.Func([IDL.Text], [ChangePasswordResult], []),
  'saveAboutContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendCallSignal' : IDL.Func(
      [IDL.Principal, CallSignalType, IDL.Text],
      [SignalId],
      [],
    ),
  'sendDirectMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SendMessageResult],
      [],
    ),
  'setCallSettings' : IDL.Func([IDL.Bool], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'setUserPhotoUrl' : IDL.Func([IDL.Text], [], []),
  'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PoemResult], []),
  'updateAdminPoem' : IDL.Func(
      [PoemId, IDL.Text, IDL.Text, IDL.Text],
      [AdminPoemResult],
      [],
    ),
  'updateNote' : IDL.Func(
      [NoteId, IDL.Text, IDL.Text, IDL.Bool],
      [NoteResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PoemId = IDL.Nat;
  const AdminPoemEntry = IDL.Record({
    'id' : PoemId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
  });
  const AdminPoemResult = IDL.Variant({
    'contentTooShort' : IDL.Null,
    'categoryTooShort' : IDL.Null,
    'titleTooShort' : IDL.Null,
    'notFound' : IDL.Null,
    'notAdmin' : IDL.Null,
    'success' : AdminPoemEntry,
  });
  const CommentId = IDL.Nat;
  const Time = IDL.Int;
  const PostComment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const CommentResult = IDL.Variant({
    'pendingReview' : IDL.Null,
    'moderationRejected' : IDL.Text,
    'textTooShort' : IDL.Null,
    'success' : PostComment,
    'unauthorized' : IDL.Null,
  });
  const ReplyId = IDL.Nat;
  const CommentReply = IDL.Record({
    'id' : ReplyId,
    'commentId' : CommentId,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const ReplyResult = IDL.Variant({
    'pendingReview' : IDL.Null,
    'commentNotFound' : IDL.Null,
    'moderationRejected' : IDL.Text,
    'textTooShort' : IDL.Null,
    'success' : CommentReply,
    'unauthorized' : IDL.Null,
  });
  const ModerationId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChangePasswordResult = IDL.Variant({
    'passwordTooShort' : IDL.Null,
    'incorrectPassword' : IDL.Null,
    'success' : IDL.Null,
  });
  const NoteId = IDL.Nat;
  const UserNote = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
    'isPublic' : IDL.Bool,
  });
  const NoteResult = IDL.Variant({
    'contentTooShort' : IDL.Null,
    'titleTooShort' : IDL.Null,
    'notFound' : IDL.Null,
    'success' : UserNote,
    'unauthorized' : IDL.Null,
  });
  const DeleteResult = IDL.Variant({
    'notFoundInAdminCollection' : IDL.Null,
    'notFoundInCommunityCollection' : IDL.Null,
    'notFound' : IDL.Null,
    'notAdmin' : IDL.Null,
    'success' : IDL.Null,
  });
  const CommentDeleteResult = IDL.Variant({
    'notFound' : IDL.Null,
    'success' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const PoemDeleteResult = IDL.Variant({
    'notFound' : IDL.Null,
    'success' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const NoteDeleteResult = IDL.Variant({
    'notFound' : IDL.Null,
    'success' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const AboutContent = IDL.Record({
    'bio' : IDL.Text,
    'poetryFragments' : IDL.Text,
    'lastUpdated' : Time,
    'poetName' : IDL.Text,
    'story' : IDL.Text,
  });
  const CallSettings = IDL.Record({ 'allowCalls' : IDL.Bool });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Theme = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const CommunityPoem = IDL.Record({
    'id' : PoemId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'suggestedTheme' : Theme,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const MessageId = IDL.Nat;
  const DirectMessage = IDL.Record({
    'id' : MessageId,
    'read' : IDL.Bool,
    'text' : IDL.Text,
    'toUser' : IDL.Principal,
    'toUsername' : IDL.Text,
    'timestamp' : Time,
    'fromUser' : IDL.Principal,
    'fromUsername' : IDL.Text,
  });
  const ModerationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'needsReview' : IDL.Null,
  });
  const ModerationEntry = IDL.Record({
    'id' : ModerationId,
    'status' : ModerationStatus,
    'content' : IDL.Text,
    'contentType' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'riskLevel' : IDL.Text,
    'reason' : IDL.Text,
  });
  const ModerationStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'approvedCount' : IDL.Nat,
    'rejectedCount' : IDL.Nat,
  });
  const SignalId = IDL.Nat;
  const CallSignalType = IDL.Variant({
    'iceCandidate' : IDL.Null,
    'offer' : IDL.Null,
    'answer' : IDL.Null,
    'hangup' : IDL.Null,
  });
  const CallSignal = IDL.Record({
    'id' : SignalId,
    'data' : IDL.Text,
    'toUser' : IDL.Principal,
    'timestamp' : Time,
    'consumed' : IDL.Bool,
    'fromUser' : IDL.Principal,
    'signalType' : CallSignalType,
  });
  const SendMessageResult = IDL.Variant({
    'textTooShort' : IDL.Null,
    'success' : DirectMessage,
    'unauthorized' : IDL.Null,
  });
  const PoemResult = IDL.Variant({
    'pendingReview' : IDL.Null,
    'contentTooShort' : IDL.Null,
    'authorNameTooShort' : IDL.Null,
    'moderationRejected' : IDL.Text,
    'titleTooShort' : IDL.Null,
    'notFound' : IDL.Null,
    'themeNameTooShort' : IDL.Null,
    'success' : CommunityPoem,
    'unauthorized' : IDL.Null,
  });
  
  return IDL.Service({
    'addAdminPoem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AdminPoemResult],
        [],
      ),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [CommentResult],
        [],
      ),
    'addReply' : IDL.Func(
        [CommentId, IDL.Text, IDL.Text, IDL.Text],
        [ReplyResult],
        [],
      ),
    'approveModeratedContent' : IDL.Func([ModerationId], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ChangePasswordResult],
        [],
      ),
    'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NoteResult], []),
    'deleteAdminPoem' : IDL.Func([PoemId], [DeleteResult], []),
    'deleteComment' : IDL.Func([CommentId], [CommentDeleteResult], []),
    'deleteMyPoem' : IDL.Func([PoemId], [PoemDeleteResult], []),
    'deleteNote' : IDL.Func([NoteId], [NoteDeleteResult], []),
    'deleteReply' : IDL.Func([ReplyId], [CommentDeleteResult], []),
    'getAboutContent' : IDL.Func([], [IDL.Opt(AboutContent)], ['query']),
    'getAdminPassword' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminPoems' : IDL.Func([], [IDL.Vec(AdminPoemEntry)], ['query']),
    'getCallSettings' : IDL.Func([IDL.Principal], [CallSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCommentsForPost' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PostComment)],
        ['query'],
      ),
    'getCommunityPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
    'getConversationByUsername' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getMessagesForUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getModerationQueue' : IDL.Func([], [IDL.Vec(ModerationEntry)], ['query']),
    'getModerationStats' : IDL.Func([], [ModerationStats], ['query']),
    'getMyNotes' : IDL.Func([], [IDL.Vec(UserNote)], ['query']),
    'getMyPendingSignals' : IDL.Func([], [IDL.Vec(CallSignal)], ['query']),
    'getMyPoems' : IDL.Func([], [IDL.Vec(CommunityPoem)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicNotesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UserNote)],
        ['query'],
      ),
    'getRepliesForComment' : IDL.Func(
        [CommentId],
        [IDL.Vec(CommentReply)],
        ['query'],
      ),
    'getUserPhotoUrl' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'login' : IDL.Func([], [UserRole], []),
    'markDirectMessageRead' : IDL.Func([MessageId], [], []),
    'markSignalConsumed' : IDL.Func([SignalId], [], []),
    'rejectModeratedContent' : IDL.Func([ModerationId, IDL.Text], [], []),
    'resetAdminPassword' : IDL.Func([IDL.Text], [ChangePasswordResult], []),
    'saveAboutContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendCallSignal' : IDL.Func(
        [IDL.Principal, CallSignalType, IDL.Text],
        [SignalId],
        [],
      ),
    'sendDirectMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SendMessageResult],
        [],
      ),
    'setCallSettings' : IDL.Func([IDL.Bool], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'setUserPhotoUrl' : IDL.Func([IDL.Text], [], []),
    'submitPoem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [PoemResult], []),
    'updateAdminPoem' : IDL.Func(
        [PoemId, IDL.Text, IDL.Text, IDL.Text],
        [AdminPoemResult],
        [],
      ),
    'updateNote' : IDL.Func(
        [NoteId, IDL.Text, IDL.Text, IDL.Bool],
        [NoteResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };