/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PoemResult = {
    __kind__: "contentTooShort";
    contentTooShort: null;
} | {
    __kind__: "authorNameTooShort";
    authorNameTooShort: null;
} | {
    __kind__: "titleTooShort";
    titleTooShort: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "themeNameTooShort";
    themeNameTooShort: null;
} | {
    __kind__: "success";
    success: CommunityPoem;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type Time = bigint;
export interface CommunityPoem {
    id: PoemId;
    title: string;
    content: string;
    suggestedTheme: Theme;
    authorName: string;
    author: Principal;
    timestamp: Time;
}
export interface AdminPoem {
    id: PoemId;
    title: string;
    content: string;
    category: string;
}
export type PoemId = bigint;
export interface Theme {
    name: string;
    description: string;
}
export interface UserProfile {
    name: string;
}
export type AdminPoemResult = {
    __kind__: "contentTooShort";
    contentTooShort: null;
} | {
    __kind__: "categoryTooShort";
    categoryTooShort: null;
} | {
    __kind__: "titleTooShort";
    titleTooShort: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "notAdmin";
    notAdmin: null;
} | {
    __kind__: "success";
    success: AdminPoem;
};
export enum DeleteResult {
    notFoundInAdminCollection = "notFoundInAdminCollection",
    notFoundInCommunityCollection = "notFoundInCommunityCollection",
    notFound = "notFound",
    notAdmin = "notAdmin",
    success = "success"
}
export enum PoemDeleteResult {
    notFound = "notFound",
    success = "success",
    unauthorized = "unauthorized"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export type ChangePasswordResult = {
    __kind__: "success";
    success: null;
} | {
    __kind__: "incorrectPassword";
    incorrectPassword: null;
} | {
    __kind__: "passwordTooShort";
    passwordTooShort: null;
};
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminPoem(title: string, content: string, category: string): Promise<AdminPoemResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAdminPoem(id: PoemId): Promise<DeleteResult>;
    deleteMyPoem(id: PoemId): Promise<PoemDeleteResult>;
    changeAdminPassword(currentPw: string, newPw: string): Promise<ChangePasswordResult>;
    getAdminPassword(): Promise<string>;
    getAdminPoems(): Promise<Array<AdminPoem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityPoems(): Promise<Array<CommunityPoem>>;
    getDisplayName(user: Principal): Promise<string | null>;
    getMyPoems(): Promise<Array<CommunityPoem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDisplayName(name: string): Promise<void>;
    submitPoem(title: string, content: string, authorName: string): Promise<PoemResult>;
    updateAdminPoem(id: PoemId, title: string, content: string, category: string): Promise<AdminPoemResult>;
}
import type { AdminPoem as _AdminPoem, AdminPoemResult as _AdminPoemResult, CommunityPoem as _CommunityPoem, DeleteResult as _DeleteResult, PoemDeleteResult as _PoemDeleteResult, PoemResult as _PoemResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminPoem(arg0: string, arg1: string, arg2: string): Promise<AdminPoemResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPoem(arg0, arg1, arg2);
                return from_candid_AdminPoemResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPoem(arg0, arg1, arg2);
            return from_candid_AdminPoemResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAdminPoem(arg0: PoemId): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminPoem(arg0);
                return from_candid_DeleteResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminPoem(arg0);
            return from_candid_DeleteResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminPoem(arg0: PoemId, arg1: string, arg2: string, arg3: string): Promise<AdminPoemResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPoem(arg0, arg1, arg2, arg3);
                return from_candid_AdminPoemResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPoem(arg0, arg1, arg2, arg3);
            return from_candid_AdminPoemResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMyPoem(arg0: PoemId): Promise<PoemDeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyPoem(arg0);
                return from_candid_PoemDeleteResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyPoem(arg0);
            return from_candid_PoemDeleteResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPassword(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPassword();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPassword();
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<ChangePasswordResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return from_candid_ChangePasswordResult(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return from_candid_ChangePasswordResult(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPoems(): Promise<Array<AdminPoem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPoems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPoems();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityPoems(): Promise<Array<CommunityPoem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityPoems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityPoems();
            return result;
        }
    }
    async getDisplayName(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayName(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayName(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPoems(): Promise<Array<CommunityPoem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPoems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPoems();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async submitPoem(arg0: string, arg1: string, arg2: string): Promise<PoemResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPoem(arg0, arg1, arg2);
                return from_candid_PoemResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPoem(arg0, arg1, arg2);
            return from_candid_PoemResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChangePasswordResult(_uploadFile: any, _downloadFile: any, value: any): ChangePasswordResult {
    return "success" in value ? { __kind__: "success", success: null }
        : "incorrectPassword" in value ? { __kind__: "incorrectPassword", incorrectPassword: null }
        : { __kind__: "passwordTooShort", passwordTooShort: null };
}
function from_candid_AdminPoemResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPoemResult): AdminPoemResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PoemDeleteResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PoemDeleteResult): PoemDeleteResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PoemResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PoemResult): PoemResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentTooShort: null;
} | {
    authorNameTooShort: null;
} | {
    titleTooShort: null;
} | {
    notFound: null;
} | {
    themeNameTooShort: null;
} | {
    success: _CommunityPoem;
} | {
    unauthorized: null;
}): {
    __kind__: "contentTooShort";
    contentTooShort: null;
} | {
    __kind__: "authorNameTooShort";
    authorNameTooShort: null;
} | {
    __kind__: "titleTooShort";
    titleTooShort: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "themeNameTooShort";
    themeNameTooShort: null;
} | {
    __kind__: "success";
    success: CommunityPoem;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "contentTooShort" in value ? {
        __kind__: "contentTooShort",
        contentTooShort: value.contentTooShort
    } : "authorNameTooShort" in value ? {
        __kind__: "authorNameTooShort",
        authorNameTooShort: value.authorNameTooShort
    } : "titleTooShort" in value ? {
        __kind__: "titleTooShort",
        titleTooShort: value.titleTooShort
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "themeNameTooShort" in value ? {
        __kind__: "themeNameTooShort",
        themeNameTooShort: value.themeNameTooShort
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentTooShort: null;
} | {
    categoryTooShort: null;
} | {
    titleTooShort: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
} | {
    success: _AdminPoem;
}): {
    __kind__: "contentTooShort";
    contentTooShort: null;
} | {
    __kind__: "categoryTooShort";
    categoryTooShort: null;
} | {
    __kind__: "titleTooShort";
    titleTooShort: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "notAdmin";
    notAdmin: null;
} | {
    __kind__: "success";
    success: AdminPoem;
} {
    return "contentTooShort" in value ? {
        __kind__: "contentTooShort",
        contentTooShort: value.contentTooShort
    } : "categoryTooShort" in value ? {
        __kind__: "categoryTooShort",
        categoryTooShort: value.categoryTooShort
    } : "titleTooShort" in value ? {
        __kind__: "titleTooShort",
        titleTooShort: value.titleTooShort
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "notAdmin" in value ? {
        __kind__: "notAdmin",
        notAdmin: value.notAdmin
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFoundInAdminCollection: null;
} | {
    notFoundInCommunityCollection: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
} | {
    success: null;
}): DeleteResult {
    return "notFoundInAdminCollection" in value ? DeleteResult.notFoundInAdminCollection : "notFoundInCommunityCollection" in value ? DeleteResult.notFoundInCommunityCollection : "notFound" in value ? DeleteResult.notFound : "notAdmin" in value ? DeleteResult.notAdmin : "success" in value ? DeleteResult.success : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    success: null;
} | {
    unauthorized: null;
}): PoemDeleteResult {
    return "notFound" in value ? PoemDeleteResult.notFound : "success" in value ? PoemDeleteResult.success : "unauthorized" in value ? PoemDeleteResult.unauthorized : value;
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
